version: '2'

services:
  es:
    container_name: es_container
    build: ./docker/elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_NODE_NAME=es_node_1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    build: ./docker/kibana
    ports:
      - "5601:5601"
    links:
      - es:elasticsearch
