in:
  type: file
  path_prefix: ./data/ml-latest-small/movies.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: movieId, type: long}
    - {name: title, type: string}
    - {name: genres, type: string}
out:
  type: elasticsearch
  nodes:
  - {host: 192.168.99.100}
  cluster_name: movielens
  index: movielines
  index_type: movies
